title: Personal Wiki
description: Cool links about random stuff I'm reading / using
remote_theme: just-the-docs/just-the-docs

# Color scheme (light/dark)
color_scheme: light

# Aux links (top right)
aux_links:
  "GitHub":
    - "https://github.com/davd-gzl/personal-wiki"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Exclude files from processing
exclude:
  - .git
  - .github
  - CONTRIBUTING.md

# Enable plugins
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings

# Plugin settings
relative_links:
  enabled: true
  collections: true

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
